version: "3.8"

services:
  capstone-db:
    image: postgres:14-alpine
    restart: always
    environment:
      - DATABASE_HOST=${PG_HOST:-127.0.0.1}
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWD:-docker}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=voyager
    ports:
      - "${PG_PORT-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  capstone-api:
    build: backend/
    depends_on:
      capstone-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - NODE_OPTIONS='--experimental-vm-modules --experimental-specifier-resolution=node'
      - NODE_ENV=development
      - FIREBASE_PATH="${FIREBASE_PATH}"
      - DATABASE_HOST=capstone-db
      - PG_USER=${PG_USER:-postgres}
      - PG_HOST=${PG_HOST:-capstone-db}
      - PG_PASSWD=${PG_PASSWD:-docker}
      - POSTGRES_PORT=${PG_PORT-5432}
      - POSTGRES_DB=capstone
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: bind
        source: ./.secrets
        target: /secrets
    command: npm run dev

  capstone-db-viewer:
    build: backend/
    depends_on:
      capstone-db:
        condition: service_healthy
    ports:
      - "8082:8081"
    environment:
      - NODE_OPTIONS='--experimental-vm-modules --experimental-specifier-resolution=node'
      - NODE_ENV=development
      - DATABASE_HOST=capstone-db
      - PG_USER=${PG_USER:-postgres}
      - PG_HOST=${PG_HOST:-capstone-db}
      - PG_PASSWD=${PG_PASSWD:-docker}
      - POSTGRES_PORT=${PG_PORT-5432}
      - POSTGRES_DB=capstone

    volumes:
      - type: bind
        source: ./backend
        target: /app
    command: npm run db:view -- --port 8081 --browser none
  capstone-ui:
    build: frontend/
    depends_on:
      - "capstone-api"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_FIREBASE_API_KEY="AIzaSyB_Ph-X_XyXlLN7fjyJhoiS73bZs-o-rfU"
      - REACT_APP_FIREBASE_AUTH_DOMAIN="bsdi-capstone.firebaseapp.com"
      - REACT_APP_FIREBASE_PROJECT_ID="bsdi-capstone"
      - REACT_APP_FIREBASE_STORAGE_BUCKET="bsdi-capstone.appspot.com"
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID="831411631880"
      - REACT_APP_FIREBASE_APP_ID="1:831411631880:web:32bf1f0ede9a30e146debd"
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
