import admin from "firebase-admin";

const {
	FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID,
	FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY,
	FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL,
	FIREBASE_SERVICE_ACCOUNT_CLIENT_ID,
	FIREBASE_SERVICE_ACCOUNT_AUTH_URI,
	FIREBASE_SERVICE_ACCOUNT_TOKEN_URI,
	FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL,
	FIREBASE_SERVICE_ACCOUNT_CLIENT_PROVIDER_X509_CERT_URL
} = process.env;

const serviceAccount = {
	type: "service_account",
	project_id: "bsdi-capstone",
	private_key_id: FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID,
	private_key: FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY,
	client_email: FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL,
	client_id: FIREBASE_SERVICE_ACCOUNT_CLIENT_ID,
	auth_uri: FIREBASE_SERVICE_ACCOUNT_AUTH_URI,
	token_uri: FIREBASE_SERVICE_ACCOUNT_TOKEN_URI,
	auth_provider_x509_cert_url:
		FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL,
	client_x509_cert_url: FIREBASE_SERVICE_ACCOUNT_CLIENT_PROVIDER_X509_CERT_URL
};

admin.initializeApp({
	credential: admin.credential.cert(serviceAccount)
});

export default admin;
