# This Workflow Builds, Tests, Lints, and Deploys the Backend to Heroku
name: CI/CD for Main branch's Backend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 'jobs' is the list of all the workflows that will kick off.
jobs:
  # This workflow kicks off the build and test for the Backend
  build-and-test:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          # optional (defaults to `postgres`)
          POSTGRES_DB: test
          # required
          POSTGRES_PASSWORD: postgres
          # optional (defaults to `5432`)
          POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_HOST: postgres
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      - name: Migrate database
        run: npm --prefix backend run db:reset -- --skip-generate --force
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test

      - name: Run tests
        run: npm --prefix backend run test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test

  # This workflow kicks off the linter for your Backend.
  lint:
    name: Lint Backend Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
      # Installs dependencies on the runner for Backend
      - name: Install linter options
        run: npm --prefix ./backend install
      # Executes the linter on the Backend code base.
      - name: Run Linter
        run: npm --prefix ./backend run lint

  # This workflow kicks off the deployment to Heroku
  deploy-to-heroku:
    name: Deploy Backend to Heroku
    if: github.event_name == 'push'
    # Needs specifies the steps that must previously complete in order to deploy your application.
    needs: [build-and-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy Backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bsdi1-voyager-backend"
          heroku_email: "dkarrick2@gmail.com"
          appdir: "backend/"
          usedocker: true
