# This Workflow Builds, Tests, Lints, and Deploys the Backend to Heroku
name: CI/CD for Main branch's Backend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 'jobs' is the list of all the workflows that will kick off.
jobs:
  # This workflow kicks off the build and test for the Backend
  build-and-test:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - run: npm --prefix backend install
      - name: Build Backend
        run: |
          docker build \
          -t capstone-api \
          ./backend
      - name: Migrate Database
        working-directory: backend
        run: |
          pg_isready -d postgres -h 172.17.0.1 -p 5432 -U postgres
          node -v
          export DATABASE_URL="postgres://postgres:postgres@172.17.0.1:5432/postgres"
          export NODE_OPTIONS="--experimental-vm-modules --experimental-specifier-resolution=node"
          npm run db:testMigration
          npm run db:seed

      - name: Test Backend
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          docker run \
          -e CI=true \
          -e DATABASE_URL="postgres://postgres:postgres@172.17.0.1:5432/postgres" \
          -e FIREBASE_SERVICE_ACCOUNT="${FIREBASE_SERVICE_ACCOUNT}" \
          capstone-api npm run test

  # This workflow kicks off the linter for your Backend.
  lint:
    name: Lint Backend Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
      # Installs dependencies on the runner for Backend
      - name: Install linter options
        run: npm --prefix ./backend install
      # Executes the linter on the Backend code base.
      - name: Run Linter
        run: npm --prefix ./backend run lint

  # This workflow kicks off the deployment to Heroku
  deploy-to-heroku:
    name: Deploy Backend to Heroku
    if: github.event_name == 'push'
    # Needs specifies the steps that must previously complete in order to deploy your application.
    needs: [build-and-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy Backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bsdi1-voyager-backend"
          heroku_email: "dkarrick2@gmail.com"
          appdir: "backend/"
          branch: main
