name: Handle User Story Submissions

on:
  issues:
    types: opened
    
concurrency: 'main'
jobs:
  get_submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: cat $GITHUB_EVENT_PATH
      - run: npm install @octokit/action
      - run: node .github/utils/user_story.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
