name: Handle User Story Submissions

on:
  issues:
    types: opened
    
concurrency: 'main'
jobs:
  get_submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/submit_user_story.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > user_story.json
      - run: cat user_story.json
