name: Handle Issue Tasks List

on:
  issues:
    types: edited
    
concurrency: 'main'
jobs:
  get_submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: cat $GITHUB_EVENT_PATH
