# This Workflow Builds, Tests, Lints, and Deploys the Frontend and Backend to Heroku
name: CI/CD for Main branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 'jobs' is the list of all the workflows that will kick off.
jobs:
  # This workflow kicks off the build and test for the UI
  build-and-test-frontend:
    # Name of the build job
    name: Build and Test Frontend
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # `steps` are the actions that will execute on this job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell to build the Frontend
      - name: Build Frontend
        run: |
          docker build -t capstone-ui ./frontend
      # Runs a set of commands using the runners shell to test the Frontend
      - name: Test Frontend
        run: |
          docker run -e CI=true capstone-ui npm run test

  # This workflow kicks off the build and test for the Backend
  build-and-test-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Backend
        run: |
          docker build -t capstone-api ./backend
      - name: Test Backend
        run: |
          docker run -e CI=true capstone-api npm run test

  # This workflow kicks off the linter for your Backend.
  run-backend-linter:
    name: Lint Backend Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
      # Installs dependencies on the runner for Backend
      - name: Install linter options
        run: npm --prefix ./backend install
      # Executes the linter on the Backend code base.
      - name: Run Linter
        run: npm --prefix ./backend run lint

  # This workflow kicks off the linter for Frontend.
  run-frontend-linter:
    name: Lint Frontend Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Installs dependencies on the runner for Frontend
      - name: Install linter options
        run: npm --prefix ./frontend install
      # Executes the linter on the Frontend code base.
      - name: Run Linter
        run: npm --prefix ./frontend run lint

  # This workflow kicks off the deployment to Heroku
  deploy-to-heroku:
    name: Deploy to Heroku
    if: github.event_name == 'push'
    # Needs specifies the steps that must previously complete in order to deploy your application.
    needs: [build-and-test-frontend, build-and-test-backend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy Backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bsdi1-voyager-backend"
          heroku_email: "dkarrick2@gmail.com"
          appdir: "backend/"
          usedocker: true
          
  # This workflow kicks off the deployment to Heroku
  deploy-frontend-to-heroku:
    name: Deploy frontend to Heroku
    if: github.event_name == 'push'
    # Needs specifies the steps that must previously complete in order to deploy your application.
    needs: [build-and-test-frontend, build-and-test-backend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm --prefix frontend install
      - run: npm --prefix frontend run build
      - name: Deploy Frontend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bsdi1-voyager-frontend"
          heroku_email: "dkarrick2@gmail.com"
          appdir: "frontend"
          buildpack: "https://github.com/heroku/heroku-buildpack-static.git"
